// Code generated by "stringer -type=ErrCode -linecomment"; DO NOT EDIT.

package message

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[OK-0]
	_ = x[Failed - -1]
	_ = x[BadRequest - -400]
	_ = x[UserNotFound - -1001]
}

const (
	_ErrCode_name_0 = "用户不存在或密码错误"
	_ErrCode_name_1 = "参数错误"
	_ErrCode_name_2 = "unknown errorok"
)

var (
	_ErrCode_index_2 = [...]uint8{0, 13, 15}
)

func (i ErrCode) String() string {
	switch {
	case i == -1001:
		return _ErrCode_name_0
	case i == -400:
		return _ErrCode_name_1
	case -1 <= i && i <= 0:
		i -= -1
		return _ErrCode_name_2[_ErrCode_index_2[i]:_ErrCode_index_2[i+1]]
	default:
		return "ErrCode(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
