// Code generated by "stringer -type=ErrCode -linecomment"; DO NOT EDIT.

package message

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[OK-0]
	_ = x[Failed - -1]
	_ = x[BadRequest - -2]
	_ = x[Unauthorized - -3]
	_ = x[UserNotFound - -1001]
	_ = x[UserExisted - -1002]
	_ = x[MusicNotFound - -1101]
	_ = x[FileUploadFailed - -1102]
}

const (
	_ErrCode_name_0 = "文件上传失败音乐不存在"
	_ErrCode_name_1 = "用户已存在用户不存在或密码错误"
	_ErrCode_name_2 = "未授权参数错误unknown errorok"
)

var (
	_ErrCode_index_0 = [...]uint8{0, 18, 33}
	_ErrCode_index_1 = [...]uint8{0, 15, 45}
	_ErrCode_index_2 = [...]uint8{0, 9, 21, 34, 36}
)

func (i ErrCode) String() string {
	switch {
	case -1102 <= i && i <= -1101:
		i -= -1102
		return _ErrCode_name_0[_ErrCode_index_0[i]:_ErrCode_index_0[i+1]]
	case -1002 <= i && i <= -1001:
		i -= -1002
		return _ErrCode_name_1[_ErrCode_index_1[i]:_ErrCode_index_1[i+1]]
	case -3 <= i && i <= 0:
		i -= -3
		return _ErrCode_name_2[_ErrCode_index_2[i]:_ErrCode_index_2[i+1]]
	default:
		return "ErrCode(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
